name: Zola on GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Build only
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: docs
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
# # On every push this script is executed
# on: push
# name: Build and deploy GH Pages
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'
#     steps:
#       - name: checkout
#         uses: actions/checkout@v2
#       - name: build_and_deploy
#         uses: shalzz/zola-deploy-action@v0.14.1
#         env:
#           # Target branch
#           PAGES_BRANCH: gh-pages
#           # Provide personal access token
#           TOKEN: ${{ secrets.TOKEN }}
